sudo: required
dist: trusty
language: bash
script:
  # Install LXD / LXC
  - sudo apt update
  - sudo apt install snapd -y
  - sudo snap install lxd
  # Configure LXD / LXC
  - sudo lxd waitready --timeout 60
  - sudo lxd init --auto;
  - sudo usermod -a -G lxd travis;
  - export PATH=/snap/bin/:${PATH}
  - lxc network create lxdbr0
  - lxc network attach-profile lxdbr0 default eth0
  # Build all images
  - sh build-all.sh
