sudo: required
dist: trusty
language: bash
script:
  # Install LXD / LXC
  - sudo apt update
  - sudo apt install snapd -y
  - sudo snap install lxd
  - sudo lxd waitready --timeout 60
  - sudo lxd init --auto;
  - sudo usermod -a -G lxd travis;
  - sudo su travis -c 'export PATH=/snap/bin/:${PATH} && sh build-all.sh';
